apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycafeapp
  labels:
    app: mycafeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mycafeapp
  template:
    metadata:
      labels:
        app: mycafeapp
    spec:
      containers:
      - name: mycafeapp
        image: karthikk007/cafeservice:v2
        ports:
        - containerPort: 80
